num = float(input("Digite seu número para a tabuada: "))

print(f"{num} x 1 = {num*1:.2f}")
print(f"{num} x 2 = {num*2:.2f}")
print(f"{num} x 3 = {num*3:.2f}")
print(f"{num} x 4 = {num*4:.2f}")
print(f"{num} x 5  = {num*5:.2f}")
print(f"{num} x 6 = {num*6:.2f}")
print(f"{num} x 7 = {num*7:.2f}")
print(f"{num} x 8 = {num*8:.2f}")
print(f"{num} x 9 = {num*9:.2f}")
print(f"{num} x 10 = {num*10:.2f}")